/** Declaration file generated by dts-gen */

export = environment_vars;

declare class environment_vars {
    constructor(pathToDotEnvFile: any, fileName: any);

    get(varName: any): any;

    getAppEnv(): any;

}

